name: Deploy Jupyter Book to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with the branch you use for your source files

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Navigate to the `pages` folder and build the Jupyter Book
    - name: Navigate to the `pages` folder and Build the Jupyter Book
      run: |
        cd pages
        jupyter-book build .

    # Ensure the CNAME file is in the built HTML directory
    - name: Add CNAME file
      run: |
        cd pages
        echo "cheat-sheets.breezy-codes.com" > _build/html/CNAME

    # Upload the book's HTML as an artifact
    - name: Upload artifact
      run: |
        cd pages
        actions/upload-pages-artifact@v2
      with:
        path: "_build/html"

    # Deploy the book's HTML to GitHub Pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2